/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_principales;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class nombre extends javax.swing.JFrame {
     public static double Diseño = 0, Sistemas = 0, Admin = 0;
     public static String total ="", nombre ="", curso="";
    public nombre() {
        initComponents();
        
       resultados.setOpaque (true);
       resultados.setBorderPainted (false);  
       resultados.setBorder (null);  
       resultados.setFocusPainted (false);
       resultados.setContentAreaFilled (false);
       
       enviodiseño.setVisible(false); //Ocultar valor diseño envio
       enviosistemas.setVisible(false); //Ocultar valor sistemas envio
       envioadmin.setVisible(false); //Ocultar valor admin envio
       recidiseño2.setVisible(false); //Ocultar valor diseño recibo
       recisistemas2.setVisible(false); //Ocultar valor sistemas recibo
       reciadmin2.setVisible(false); //Ocultar valor admin recibo
       
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Iconos/Logo2.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        recidiseño2 = new javax.swing.JTextField();
        enviodiseño = new javax.swing.JTextField();
        recisistemas2 = new javax.swing.JTextField();
        enviosistemas = new javax.swing.JTextField();
        reciadmin2 = new javax.swing.JTextField();
        envioadmin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nombre1 = new javax.swing.JTextField();
        curso1 = new javax.swing.JTextField();
        resultados = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nota.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 260, -1));
        jPanel1.add(recidiseño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, -1));
        jPanel1.add(enviodiseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 50, -1));
        jPanel1.add(recisistemas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 50, -1));
        jPanel1.add(enviosistemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 50, -1));
        jPanel1.add(reciadmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 50, -1));
        jPanel1.add(envioadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 50, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 190, 50));

        nombre1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 380, 50));

        curso1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 380, 50));

        resultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resultados.png"))); // NOI18N
        resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosActionPerformed(evt);
            }
        });
        jPanel1.add(resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Home.png"))); // NOI18N
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 40, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 130, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Nombre.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void resultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosActionPerformed
        nombre=nombre1.getText();
        curso=curso1.getText();
        Diseño=Double.valueOf(recidiseño2.getText());
        Sistemas=Double.valueOf(recisistemas2.getText());
        Admin=Double.valueOf(reciadmin2.getText());
        
       if(Diseño>Sistemas&&Diseño>Admin){
       total=("Diseño");
       }
       else if(Sistemas>Diseño&&Sistemas>Admin){
       total=("Sistemas");
       }
       else{
       total=("Administración");
       }
        
        
        if(nombre1.getText().equals("") || curso1.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Debes llenar ambos campos", "Atención", 2);
       enviodiseño.setText(recidiseño2.getText());
       enviosistemas.setText(recisistemas2.getText());
       envioadmin.setText(reciadmin2.getText());
        }
        else{
        new fin().setVisible(true);
        this.setVisible(false);
            

        
        

       
        }
    }//GEN-LAST:event_resultadosActionPerformed

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JTextField curso1;
    public static javax.swing.JTextField envioadmin;
    public static javax.swing.JTextField enviodiseño;
    public static javax.swing.JTextField enviosistemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nombre1;
    public static javax.swing.JTextField reciadmin2;
    public static javax.swing.JTextField recidiseño2;
    public static javax.swing.JTextField recisistemas2;
    private javax.swing.JButton resultados;
    // End of variables declaration//GEN-END:variables
}
