/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_principales;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author ESTUDIANTE
 */
public class Orientacion extends javax.swing.JFrame {
    String nombre="", curso1="", observacion1="";
    HSSFRow fila, fila2;
    String rellenado[][];
    
    public Orientacion() {
        initComponents();
       aplicar.setOpaque (true);
       aplicar.setBorderPainted (false);  
       aplicar.setBorder (null);  
       aplicar.setFocusPainted (false);
       aplicar.setContentAreaFilled (false);
        
       arch1.setOpaque (true);
       arch1.setBorderPainted (false);  
       arch1.setBorder (null);  
       arch1.setFocusPainted (false);
       arch1.setContentAreaFilled (false); 
       
       arch2.setOpaque (true);
       arch2.setBorderPainted (false);  
       arch2.setBorder (null);  
       arch2.setFocusPainted (false);
       arch2.setContentAreaFilled (false);        
       
    }
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Iconos/Logo2.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        arch2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        arch1 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        aplicar = new javax.swing.JButton();
        estudiante = new javax.swing.JTextField();
        curso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setToolTipText("");

        observacion.setColumns(20);
        observacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        observacion.setRows(5);
        jScrollPane1.setViewportView(observacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 580, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        arch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arch2.png"))); // NOI18N
        arch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arch2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(arch2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(arch2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 174, 170, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        arch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arch1.png"))); // NOI18N
        arch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arch1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(arch1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 170, 120));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Home.png"))); // NOI18N
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 40, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        aplicar.setBackground(new java.awt.Color(255, 255, 255));
        aplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aplicar.png"))); // NOI18N
        aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 150, 50));

        estudiante.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 430, 40));

        curso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 155, 430, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/orientacion.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarActionPerformed
       nombre=estudiante.getText();
       curso1=curso.getText();
       observacion1=observacion.getText();
       int ctotal=0, stop=0, existe=0;
       
       
try{ //Prueba
FileInputStream carga=new FileInputStream(new File("Observaciones.xls"));
    HSSFWorkbook libro=new HSSFWorkbook(carga);  
    HSSFSheet hoja = libro.getSheetAt(0);
    fila = hoja.getRow(1);
    double goku=Double.valueOf(String.valueOf(fila.getCell(3)));
existe=1;
}catch(Exception a){
stop=1;
}


try{ //Ejecucion

    ejecucion:{
    if(stop==1){
break ejecucion;
    
}
//Guardar en matriz
    FileInputStream carga=new FileInputStream(new File("Observaciones.xls")); 
    HSSFWorkbook libro=new HSSFWorkbook(carga);  
    HSSFSheet hoja = libro.getSheetAt(0);
    fila = hoja.getRow(1);
    double goku=Double.valueOf(String.valueOf(fila.getCell(3)));
    ctotal=(int)(Math.floor(goku));

        rellenado=new String[ctotal+1][3];
            for(int i=0; i<(ctotal+1); i++){
            fila=hoja.getRow(i);
                for(int j=0; j<3; j++){
                rellenado[i][j]=String.valueOf(fila.getCell(j));
                }}

//Sobreescribir
    HSSFWorkbook libro2 = new HSSFWorkbook();    
    HSSFSheet hoja2 = libro2.createSheet("Observaciones");        

    
        for(int i=0; i<(ctotal+1); i++){
        fila2 = hoja2.createRow(i);
             for(int j=0;j<3;j++){
                 if(i==0){ fila2.createCell(3).setCellValue("N°Registrado");}
                 if(i==1){ fila2.createCell(3).setCellValue(ctotal+1);}
             fila2.createCell(j).setCellValue(rellenado[i][j]);   
             
            }}
        
       
fila2=hoja2.createRow(ctotal+1);
if((ctotal+1)==1){fila2.createCell(3).setCellValue(ctotal+1);}
fila2.createCell(0).setCellValue(nombre);
fila2.createCell(1).setCellValue(curso1);
fila2.createCell(2).setCellValue(observacion1);



//Exportar archivo
    FileOutputStream arch = new FileOutputStream("Observaciones.xls");
    libro2.write(arch);
    arch.close();
    


    

}}catch (Exception e){
    System.out.println("Aarón la cagaste");}       


try{//Si no existe
    noExiste:{
    if(existe==1){
        break noExiste;}
    HSSFWorkbook libro3 = new HSSFWorkbook();    
    HSSFSheet hoja3 = libro3.createSheet("Observaciones");

    
    fila2=hoja3.createRow(0);
    fila2.createCell(0).setCellValue("Nombre del estudiante");
    fila2.createCell(1).setCellValue("Curso");
    fila2.createCell(2).setCellValue("Observación");
    fila2.createCell(3).setCellValue("N°Registrados");
    
    fila2=hoja3.createRow(1);
    fila2.createCell(0).setCellValue(nombre);
    fila2.createCell(1).setCellValue(curso1);
    fila2.createCell(2).setCellValue(observacion1);
    fila2.createCell(3).setCellValue(1);

    
    FileOutputStream josue = new FileOutputStream("Observaciones.xls");
    libro3.write(josue);
    josue.close();
    } 
}catch(Exception e){
System.out.println("No funcionó");}
       


       estudiante.setText("");
       curso.setText("");
       observacion.setText("");
       System.out.println(ctotal);
    }//GEN-LAST:event_aplicarActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void arch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arch1ActionPerformed
        try{
            String archivo="Resultados.xls";
            String rutaAbsoluta = new File(archivo).getAbsolutePath();

          Runtime.getRuntime().exec("cmd /c start "+rutaAbsoluta);
          }catch(IOException  e){
          JOptionPane.showMessageDialog(null, "No se ha encontrado el fichero", "Error", 2);
          }
    }//GEN-LAST:event_arch1ActionPerformed

    private void arch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arch2ActionPerformed
                try{
            String archivo="Observaciones.xls";
            String rutaAbsoluta = new File(archivo).getAbsolutePath();

          Runtime.getRuntime().exec("cmd /c start "+rutaAbsoluta);
          }catch(IOException  e){
          JOptionPane.showMessageDialog(null, "No se ha encontrado el fichero", "Error", 2);
          }
    }//GEN-LAST:event_arch2ActionPerformed

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orientacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orientacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orientacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orientacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orientacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton aplicar;
    private javax.swing.JButton arch1;
    private javax.swing.JButton arch2;
    private javax.swing.JTextField curso;
    private javax.swing.JTextField estudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea observacion;
    // End of variables declaration//GEN-END:variables
}
